[colors.primary]
background = "#262626"
foreground = "#e1e1e1"
dim_foreground = "#7f849c"
bright_foreground = "#e1e1e1"

[colors.cursor]
text = "#262626"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#262626"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#262626"
background = "#b7b7b7"

[colors.search.focused_match]
foreground = "#262626"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#262626"
background = "#b7b7b7"

[colors.hints.start]
foreground = "#262626"
background = "#f9e2af"

[colors.hints.end]
foreground = "#262626"
background = "#b7b7b7"

[colors.selection]
text = "#262626"
background = "#f5e0dc"

[colors.normal]
black = "#505050"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#cccccc"

[colors.bright]
black = "#646464"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#b7b7b7"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
